name: ai_llm_chat_example
description: >-
  Sample apps showing off various features of the Flutter AI Toolkit.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: '>=3.27.0-0'

dependencies:
  ai_llm_chat:
    path: ..
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  firebase_ai: ^2.0.0
  firebase_core: ^3.13.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.3
  future_builder_ex: ^5.0.0
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  solar_icons: ^0.0.5
  split_view: ^3.2.1
  url_launcher: ^6.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/recipes_default.json
    - assets/halloween-bg.png
